schema:
  source: local
  path: schema.graphql
introspection:
  introspect:
    enabled: true
  execute:
    enabled: true
transport:
  type: streamable_http
  stateful_mode: false
  # This is for development. In production, you probably want to remove this!
  host_validation:
    enabled: false
overrides:
  mutation_mode: "all"
